SC_uint(_Enable, 0, [SCInHeader][SCToggle][SCConstValue(1,pixel)], "", "")

SC_uint(_InternalMode, 0, [SCEnum(Heightmap, 0, LayerAlpha, 1)], "Mode", "")
SC_uint(_InternalSurfaceBlend, 0, [SCEnum(Add, 0, Replace, 1)], "Surface Blend", "")
SC_Texture2D(_InternalMap, "black", [], "Internal Map", "")
SC_ScaleOffset(_InternalMap)
SC_uint(_InternalUV, 0, [SCEnum(UV0, 0, UV1, 1, UV2, 2, UV3, 3)], "__UV", "")
SC_float4(_InternalDepth, (0,0.02,0,0), [SCMinMax(0,0.1)], "Depth Range", "")
SC_float(_InternalFadeNear, 1, [SCRange(0,5)], "Brightness (Near)", "")
SC_float(_InternalFadeFar, 0.1, [SCRange(0,5)], "Brightness (Far)", "")
SC_color(_InternalColorNear, (1,1,1,1), [HDR], "Color (Near)", "")
SC_color(_InternalColorFar, (1,1,1,1), [HDR], "Color (Far)", "")
SC_float(_InternalStrength, 1, [SCRange(0,4)], "Strength", "")
SC_uint(_InternalLit, 1, [SCToggle], "Lit", "")
SC_uint(_InternalIterations, 8, [SCRangeInt(1,32)], "Layers", "")
